### ISSUE TITLE
add example for offline emissions

### ISSUE THREAD

**Issue by gredvis** [C2SM-RCM/cosmo-emission-processing#1]
Hi Gerrit, could you please add in the readme file an example for the production of hourly offline emission files?

**Comment by gkuhl** [comment]
The examples are all described in the [cases/README.md](https://github.com/C2SM-RCM/cosmo-emission-processing/blob/master/cases/README.md) in the case folder, but we might want to mention and link them in the top-level README file.

**Comment by mjaehn** [comment]
To close this issue, I suggest this should be done in pull request https://github.com/C2SM-RCM/cosmo-emission-processing/pull/5
We should add something like this at the bottom of "Quickstart":

> Further examples, including the generation of offline files and inventory merging, can be found in [cases/README.md](https://github.com/C2SM-RCM/cosmo-emission-processing/blob/master/cases/README.md)
